;;; chat-credentials-test.el --- Request-time credentials -*- lexical-binding: t; -*-
;; Run: emacs --batch -Q -l init.el -l test/chat-credentials-test.el -f ert-run-tests-batch-and-exit
(require 'ert)
(require 'cl-lib)
(require 'shell-maker)

(ert-deftest ai-provider-table-covers-org-ai-services ()
  (dolist (service '(openai anthropic google))
    (should (assq service ian/ai-providers))
    (should (stringp (plist-get (alist-get service ian/ai-providers) :host)))))

(ert-deftest host-entry-lookup ()
  (cl-letf (((symbol-function 'ian/authinfo-secret)
             (lambda (host &optional user)
               (and (equal "ollama" host) (equal "host" user) "10.0.0.9:11434"))))
    (should (equal "10.0.0.9:11434" (ian/get-host "ollama")))
    (should (equal "10.0.0.9:11434" (ian/get-host "ollama" t)))
    (should (null (ian/get-host "missing" t)))
    (should-error (ian/get-host "missing"))))

(ert-deftest ai-available-provider-preference-order ()
  (let ((keys nil))
    (cl-letf (((symbol-function 'ian/ai-key)
               (lambda (provider &optional noerror)
                 (or (cdr (assq provider keys))
                     (unless noerror (error "Missing synthetic key"))))))
      (should (eq 'openai-compatible (ian/ai-available-provider)))
      (setq keys '((anthropic . "synthetic")))
      (should (eq 'claude (ian/ai-available-provider)))
      (setq keys '((openai . "synthetic")))
      (should (eq 'openai (ian/ai-available-provider)))
      (setq keys '((openai . "synthetic")
                   (anthropic . "synthetic")))
      (should (eq 'openai (ian/ai-available-provider))))))

(ert-deftest chat-credentials-follow-changes-without-reloading ()
  (let ((keys nil) (lookups 0)
        (shell-maker-root-path (make-temp-file "chat-credentials-" t)))
    (with-temp-file (expand-file-name ".chatgpt-shell.el" shell-maker-root-path)
      (insert "nil\n"))
    (cl-letf (((symbol-function 'ian/ai-key)
               (lambda (provider &optional noerror)
                 (cl-incf lookups)
                 (or (cdr (assq provider keys))
                     (unless noerror (error "Missing synthetic key")))))
              ((symbol-function 'ian/get-ollama-models) (lambda (&rest _) '("test")))
              (ian/ollama-host--value "ollama.test:11434"))
      (require 'gptel)
      (require 'minuet)
      (require 'chatgpt-shell)
      (require 'dall-e-shell)
      (require 'org-ai)
      (should (= lookups 0))
      ;; Backend registration must survive missing credentials.
      (dolist (backend (list gptel-openai-backend gptel-anthropic-backend
                             gptel-gemini-backend))
        (should (functionp (gptel-backend-key backend)))
        (should-error (gptel--get-api-key (gptel-backend-key backend))))
      (dolist (value '("synthetic-first" "synthetic-rotated"))
        (setq keys (mapcar (lambda (provider) (cons provider value))
                          '(openai anthropic google)))
        (dolist (backend (list gptel-openai-backend gptel-anthropic-backend
                               gptel-gemini-backend))
          (should (equal value (gptel--get-api-key (gptel-backend-key backend)))))
        (should (equal value (chatgpt-shell-openai-key)))
        (should (equal value (dall-e-shell-openai-key)))
        (should (equal value (org-ai--openai-get-token 'openai)))
        (should (equal value (funcall (plist-get minuet-openai-options :api-key))))
        (should (equal value (funcall (plist-get minuet-claude-options :api-key)))))
      ;; Stop at context creation: selection has happened; no request is sent.
      (cl-letf (((symbol-function 'minuet--get-context)
                 (lambda () (throw 'selected minuet-provider)))
                ((symbol-function 'minuet--cleanup-suggestion) #'ignore))
        (dolist (command '(minuet-show-suggestion minuet-complete-with-minibuffer))
          (dolist (scenario '((nil . openai-compatible)
                              (((anthropic . "synthetic")) . claude)
                              (((openai . "synthetic")) . openai)
                              (nil . openai-compatible)))
            (setq keys (car scenario))
            (should (eq (cdr scenario) (catch 'selected (funcall command))))))))))
